"""Generate a purchase order PDF. Falls back to HTML if weasyprint unavailable."""
from datetime import datetime


def generate_order_pdf(order_data: dict) -> bytes:
    html = _build_html(order_data)
    try:
        from weasyprint import HTML
        return HTML(string=html).write_pdf()
    except ImportError:
        # Vercel doesn't have weasyprint — return HTML with Content-Type set by caller
        return html.encode("utf-8")


def _build_html(data: dict) -> str:
    items_html = "".join(
        f"""<tr>
            <td>{item.get('product_name', '')}</td>
            <td>{item.get('sku', '')}</td>
            <td>{item.get('unit_size', '')}</td>
            <td style="text-align:center">{item.get('quantity', 0)}</td>
            <td style="text-align:right">${float(item.get('unit_price', 0)):.2f}</td>
            <td style="text-align:right">${float(item.get('line_total', 0)):.2f}</td>
        </tr>"""
        for item in data.get("items", [])
    )

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; font-size: 12px; color: #333; margin: 40px; }}
  h1 {{ color: #1a1a2e; font-size: 24px; margin-bottom: 4px; }}
  .meta {{ color: #666; margin-bottom: 24px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
  th {{ background: #1a1a2e; color: white; padding: 10px 8px; text-align: left; }}
  td {{ padding: 8px; border-bottom: 1px solid #eee; }}
  tr:nth-child(even) td {{ background: #f9f9f9; }}
  .total {{ font-size: 16px; font-weight: bold; text-align: right; margin-top: 16px; }}
  .footer {{ margin-top: 40px; font-size: 10px; color: #999; text-align: center; }}
</style>
</head>
<body>
  <h1>Purchase Order</h1>
  <div class="meta">
    <strong>To:</strong> {data.get('company_name', '')}<br>
    <strong>Order Month:</strong> {data.get('order_month', '')}<br>
    <strong>Generated:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC
  </div>
  <table>
    <thead>
      <tr>
        <th>Product</th><th>SKU</th><th>Size</th>
        <th style="text-align:center">Cases</th>
        <th style="text-align:right">Unit Price</th>
        <th style="text-align:right">Total</th>
      </tr>
    </thead>
    <tbody>{items_html}</tbody>
  </table>
  <div class="total">Grand Total: ${float(data.get('subtotal', 0)):.2f}</div>
  <div class="footer">Generated by LiquorStore Pro</div>
</body>
</html>"""
